version: '3.8'

services:
  backend:
    build:
      context: ./api-entregas
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./web-entregas
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  mobile:
    build:
      context: ./app-entregas
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=entregas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 