services:
  - type: web
    name: api-entregas
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f prisma/reset.sql
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: api-entregas-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: api-entregas-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: api-entregas-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: api-entregas-db
          property: database