services:
  - type: web
    name: api-entregas
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      psql $DATABASE_URL -f prisma/init.sql
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false